### PR TITLE
Compile with GHC8

### PR DESCRIPTION
**Pull request by charleso**
/cc @tmcgilchrist @reiddraper 

Not sure if there's a better/official way to manage multiple stack files? Seems less useful to have a separate branch that people need to checkout. Thoughts/suggestions?

### CODE REVIEW

**Comment by reiddraper** [comment]
`stack --help` suggests there's a `[--stack-yaml STACK-YAML]` option. So maybe we could check in a `stack.yaml.ghc8` file, or something?

**Comment by tmcgilchrist** [comment]
Having multiple stack yamls for each stack age release / ghc is how I've
seen it done before.

**Comment by charleso** [comment]
Have renamed to `stack-ghc8.yaml`, that seems to be the most common variation.

**Comment by reiddraper** [comment]
Perfect, thanks.

**Comment by tmcgilchrist** [comment]
🌽

**Pull request merged**
