### PR TITLE
Specify version ranges to pacify stackage.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Attempting to pacify stockage build errors without completely removing upper bounds.

### CODE REVIEW

**Comment by reiddraper** [comment]
Thanks!

**Comment by tmcgilchrist** [comment]
Would you mind doing a point release of airship to hackage so I can point stackage at it?

**Comment by reiddraper** [comment]
@tmcgilchrist I'd say we need more than a point release, since all of the new mmorph-like stuff has gone in. That OK?

**Comment by tmcgilchrist** [comment]
Of course, we're using our own fork so I forgot those things aren't up on hackage.

Changes here , https://github.com/helium/airship/compare/v0.3.0.0...master

**Comment by reiddraper** [comment]
cool, thanks @tmcgilchrist

**Comment by reiddraper** [comment]
@tmcgilchrist I've released 0.4.0.0 on Hackage. Btw, stack made it _much_ easier to upload things to hackage.

**Pull request merged**
