### PR TITLE
Setup Read the Docs.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
I am missing the correct permissions to enable GitHub web hooks for this repository.
Sending email to Helium contacts to either get permission or transfer ownership over to my personal account so I can maintain it there.

**Comment by reiddraper** [comment]
👋 , just added you as an admin, @tmcgilchrist. Give that a shot again, now?

**Comment by tmcgilchrist** [comment]
Thanks @reiddraper

**Comment by tmcgilchrist** [comment]
I have permissions and have setup the web hook I need.

**Pull request closed without merging**
