### PR TITLE
Import http-date's utcTimeToRfc1123 function.

### PR DESCRIPTION
**Pull request by patrickt**
Another additional 35% reqs/second improvement.

Before:

```
Running 2m test @ http://localhost:3000/
  1 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   335.75us  221.81us  25.10ms   96.93%
    Req/Sec    23.27k     1.71k   28.00k    80.42%
  2778439 requests in 2.00m, 0.98GB read
Requests/sec:  23153.75
Transfer/sec:      8.38MB
```

After:

```
Running 2m test @ http://localhost:3000/
  1 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   267.73us  361.03us  39.96ms   99.19%
    Req/Sec    29.74k     3.99k   35.91k    63.17%
  3550827 requests in 2.00m, 1.26GB read
Requests/sec:  29590.07
Transfer/sec:     10.71MB
```

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Looks good to me. +1

**Comment by tmcgilchrist** [comment]
Curious why you can't just re-use that library?

**Comment by reiddraper** [comment]
I believe the difference is in working w/ `UTCTime` vs `http-date`'s `HTTPDate` type.

**Comment by tmcgilchrist** [comment]
Curious if you've seen [thyme](https://hackage.haskell.org/package/thyme) which aims to provide a faster time implementation. 

My main concern is adding date/time parsing into airship directly, where it could live in it's own library. If the existing solutions don't work in this case (speed / data types), then I feel you're completely justified to build your own.

**Comment by reiddraper** [comment]
@tmcgilchrist `thyme` definitely looks neat. We have (so far) been happy using `UTCTime` everywhere, and though that that would be the best thing to support for Airship. However, definitely open to re-evaluating that.

**Comment by kellymclaughlin** [comment]
It seems that maybe `thyme` isn't being well supported at the moment. The build is marked as failing on the github repo and the last commit was back in April. Maybe the prudent move is to roll with this change for now and keep on eye on `thyme` to see if support picks up on it and try to get an RFC1123 helper submitted there if it does or make a switch to a library if we find one with suitable data types and performance.

**Comment by charleso** [comment]
👍  although an property for testing against the old/slow behaviour probably couldn't hurt

**Comment by patrickt** [comment]
I tested out a version with `thyme`; beyond incurring several extra dependencies, it is not as fast as the http-date version.

**Comment by tmcgilchrist** [comment]
Cool. Merge away :camel:

**Pull request merged**
