### PR TITLE
Export lenses for Airship.Resource

### PR DESCRIPTION
**Pull request by reiddraper**
Note, this is not backward compatible, as it change the record field
names to be underscore-prefixed.

Thoughts, @kellymclaughlin, @patrickt, @charleso, @tmcgilchrist?

### CODE REVIEW

**Comment by charleso** [comment]
I wouldn't say I'm the biggest fan of this from a "UI" perspective. At least if you're constructing the records instead of using lens'.

Another suggestion could be to keep the old names, but then have `Airship.Lens` which would have same names but could be imported additionally as qualified. Or something like that. (Not sure if that works with the lens generation or not).

No strong opinion though.

**Comment by tmcgilchrist** [comment]
Having ported a bunch of our apps across to Airship recently. I don't see that I'd use the lens functionality on `Resource` in most (perhaps all) of those projects. The main impact would be renaming the fields which is fairly simple using emacs.

So really for me I don't mind. I do wonder how people would end up using Lenses on the `Resource` record. Most of our code has ended up as:

``` haskell
createFoo :: MonadIO m => Db -> Resource m
createFoo db = defaultResource
  { allowedMethods = pure [ HTTP.methodPost]
  , processPost = createFoo' db}

createFoo' :: MonadIO m => Db -> Webmachine m (PostResponse m)
createFoo' db = do
   ....
```

**Comment by reiddraper** [comment]
@charleso @tmcgilchrist thanks. I think I'm inclined to agree with you both. Thinking about this more, the lenses would only really be helpful if these are nested records, which, they likely won't ever be.

**Comment by reiddraper** [comment]
The majority viewpoint is that this hurts more than it helps. Closing.

**Pull request closed without merging**
