### PR TITLE
Bump mmorph bounds for stackage.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Minimal changes required to satisfy the latest stackage things.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
https://github.com/fpco/stackage/issues/2529

**Comment by tmcgilchrist** [comment]
@reiddraper any chance of merging and releasing this for stackage purposes?

**Comment by reiddraper** [comment]
@tmcgilchrist I'm no longer at Helium, so don't have access to this repository currently. Maybe @madninja or @Vagabond can give us access? Otherwise we can create a new org to collaborate on Airship.

**Comment by madninja** [comment]
@reiddraper Added you as an admin colllaborator to the repo. Feel free to add other collaborators as you see fit

**Comment by tmcgilchrist** [comment]
Didn't realize that Reid.

Thanks for merging and updating. Happy to do any admin around hackage and
the project if you want.

**Pull request merged**
