### PR TITLE
Remove fromJust and add newtypes for match headers

### PR DESCRIPTION
**Pull request by charleso**
As per https://github.com/helium/airship/issues/55

Death to partial functions :)

### CODE REVIEW

**Comment by charleso** [comment]
FYI, if you're interested we _always_ use `-XNoImplicitPrelude` on all our projects and have defined our own shared version that hides all those pesky unsafe functions. That way it's even more obvious when we're being naughty. :)

https://github.com/ambiata/p/blob/master/src/P.hs

**Comment by reiddraper** [comment]
Other than merge conflicts, +1 from me.

**Comment by tmcgilchrist** [comment]
Nice work @charleso, partial functions are evil.

**Comment by reiddraper** [comment]
Thanks!

**Pull request merged**
